### ISSUE TITLE
missing BOM material

### ISSUE THREAD

**Issue by Garabito** [ole00/afterburner#1]
Hi, your proyect is excelente, but is missing the bom Material to replay it, because i dont know the value for resistors, capacitors. Can you tell me this? or can you up the schematic to check it?

Thank you very much

**Comment by ole00** [comment]
Hi, thanks. I've added the BOM. See bom.txt file. I hope no component is missing. You can cross check the schematics for the resistor and capacitor values.

**Comment by Garabito** [comment]
Thanks a lot

**Comment by Garabito** [comment]
It works excellently well, it is a great contribution
Thanks

**Comment by ole00** [comment]
I'm glad you found the project useful. Thanks for the report.
