### ISSUE TITLE
GAL22V10D support?

### ISSUE THREAD

**Issue by sanlun777** [ole00/afterburner#27]
Only the D version is readily available where i am. Has it been tested? The docs only list the B version (GAL22V10B).
Haven't had a chance to test it myself yet, as i'm missing some IC and waiting for it to arrive, but seeing all the compatibility with something not supported issues, thought it would be nice to ask first.

**Comment by ole00** [comment]
Yes, the D version works. Just tried it and it erases and programs fine.
![20230420_221729](https://user-images.githubusercontent.com/13712137/233493086-fcf0a8dc-0bc9-46b8-be54-f4e4c50fa079.jpg)

**Comment by sanlun777** [comment]
Well, that was fast, this is fantastic news! Thanks so much for the fast response and for your time. Closing now
