### ISSUE TITLE
mcp4131_read() returns incorrect wiper value when using an MCP4151 pot

### ISSUE THREAD

**Issue by hubertushirsch** [ole00/afterburner#48]
Hi,

I found a bug in the Arduino sketch for the Afterburner in the module **aftb_mcp4131.h**.

You have a function **mcp4131_read(A)**, which is a wrapper for the function **mcp4131_reg((A), 0, 1)**.
This function is used in **mcp4131_detect()** to detect whether an MCP4131 or an MCP4151 pot is present.
When **mcp4131_detect()** is executed, the variable **mcp4151_detected** is still 0 (zero) and **mcp4131_read(A)** reads back the native wiper value from the pot. That's ok here. If an MCP4151 pot was detected, **mcp4151_detected** is set to 1, for an MCP4131 the value remains at zero.

Subsequent calls to **mcp4131_reg()** via **mcp4131_write()** multiply the wiper value by 2 if **mcp4151_detected == 1**.
Likewise, calls via **mcp4131_read()** should divide the read wiper value by 2.

Here is the bug. The wiper value read is in the variable **r**.
However, the code divides the argument **value** of the function call (which is always 0 with **mcp4131_read()**) by 2.
The correct way would be to divide **r** by 2.

The code in aftb_mcp4131.h
```
94 if (mcp4151_detected && address == ADDR_WIPER && read_reg) {
95   value >>= 1; //divide the wiper value by 2
96 }
```
should be
```
94 if (mcp4151_detected && address == ADDR_WIPER && read_reg) {
95   r >>= 1; //divide the wiper value by 2
96 }
```
The bug only affects the **varVppSetVppIndex()** function, but only if an MCP4151 pot is installed and the debug option **VPP_PARANOID** is activated. The bug has no effect on normal operation.

Greetings
Hubert

**Comment by ole00** [comment]
Hi Hubert, 
well spotted, thanks for that and for the explanation. It's now fixed - see commit 2b1b34f.
